"""empty message

Revision ID: 0cdef17cf172
Revises: 4d3df1da2a76
Create Date: 2025-07-07 13:27:28.912648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdef17cf172'
down_revision = '4d3df1da2a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active_to', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('active_to')
        batch_op.drop_column('active_from')

    # ### end Alembic commands ###
