"""add url_scheduling

Revision ID: 20108f9cafe2
Revises: 2d90da9a15d5
Create Date: 2025-07-12 03:45:27.427333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20108f9cafe2'
down_revision = '2d90da9a15d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_scheduling_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('url_scheduling_data')

    # ### end Alembic commands ###
