"""empty message

Revision ID: 21405efa081f
Revises: f99248f13a1d
Create Date: 2025-07-09 03:48:09.731878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21405efa081f'
down_revision = 'f99248f13a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('active_start_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('active_end_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('active_end_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('active_start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
