"""empty message

Revision ID: 2d90da9a15d5
Revises: a93df4261b7e
Create Date: 2025-07-11 15:00:41.522879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d90da9a15d5'
down_revision = 'a93df4261b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imap_server', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_username', sa.String(length=255), nullable=False),
    sa.Column('imap_password', sa.String(length=255), nullable=False),
    sa.Column('mailbox', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imap_config')
    # ### end Alembic commands ###
