"""empty message

Revision ID: 307e81ce8cb5
Revises: ea8bfefbcbf0
Create Date: 2025-07-09 15:32:14.994368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307e81ce8cb5'
down_revision = 'ea8bfefbcbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_redirect_windows', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('scheduled_redirect_windows')

    # ### end Alembic commands ###
