"""Future model changes

Revision ID: 4d3df1da2a76
Revises: 
Create Date: 2025-07-07 12:21:00.187161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d3df1da2a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approval_requested_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_requested_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('approved_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
