"""empty message

Revision ID: 67c72c8c8e18
Revises: 21405efa081f
Create Date: 2025-07-09 04:20:51.372574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67c72c8c8e18'
down_revision = '21405efa081f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('active_start_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('active_end_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.alter_column('scheduled_active_from',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_active_to',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.alter_column('scheduled_active_to',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_active_from',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('active_end_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('active_start_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
