"""add payout countries,description in offerfromurltester

Revision ID: 6d1eaa4964b9
Revises: 20108f9cafe2
Create Date: 2025-07-12 05:23:29.129601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1eaa4964b9'
down_revision = '20108f9cafe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('countries', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('countries')
        batch_op.drop_column('payout')

    # ### end Alembic commands ###
