"""Add masked URLs to OffersFromUrlTester

Revision ID: 74e14170f90b
Revises: e388adc49946
Create Date: 2025-07-08 15:11:52.811191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e14170f90b'
down_revision = 'e388adc49946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masked_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('masked_target_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('masked_target_url')
        batch_op.drop_column('masked_image_url')

    # ### end Alembic commands ###
