"""empty message

Revision ID: 90499e251cc3
Revises: 307e81ce8cb5
Create Date: 2025-07-09 16:38:03.048212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90499e251cc3'
down_revision = '307e81ce8cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('scheduled_redirect_windows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_redirect_windows', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
