"""empty message

Revision ID: 9d9373ccb47b
Revises: 0cdef17cf172
Create Date: 2025-07-07 16:11:17.804310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9373ccb47b'
down_revision = '0cdef17cf172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('redirect_links')

    # ### end Alembic commands ###
