"""empty message

Revision ID: e388adc49946
Revises: 856739a69c4e
Create Date: 2025-07-08 09:40:28.906189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e388adc49946'
down_revision = '856739a69c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('active_end_time', sa.Time(), nullable=True))
        batch_op.drop_column('active_to')
        batch_op.drop_column('active_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_from', mysql.TIME(), nullable=True))
        batch_op.add_column(sa.Column('active_to', mysql.TIME(), nullable=True))
        batch_op.drop_column('active_end_time')
        batch_op.drop_column('active_start_time')

    # ### end Alembic commands ###
