"""empty message

Revision ID: ea8bfefbcbf0
Revises: 67c72c8c8e18
Create Date: 2025-07-09 12:30:07.881196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea8bfefbcbf0'
down_revision = '67c72c8c8e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_redirect_urls', sa.Text(), nullable=True))
        batch_op.drop_column('scheduled_redirect_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_redirect_url', mysql.TEXT(), nullable=True))
        batch_op.drop_column('scheduled_redirect_urls')

    # ### end Alembic commands ###
