"""empty message

Revision ID: f99248f13a1d
Revises: 74e14170f90b
Create Date: 2025-07-09 00:26:46.776531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99248f13a1d'
down_revision = '74e14170f90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_redirect_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_active_from', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_active_to', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers_from_url_tester', schema=None) as batch_op:
        batch_op.drop_column('scheduled_active_to')
        batch_op.drop_column('scheduled_active_from')
        batch_op.drop_column('scheduled_redirect_url')

    # ### end Alembic commands ###
